Compute localpart and domain only when needed
GaryJones/EmailAddress pull request #1
Opened 2016-09-15 09:41 UTC by GaryJones

2016-09-15 11:29 UTC, schlessera commented on src/EmailAddress.php
> +            $this->domain = str_replace($this->localpart.'@', '', $this->address);
`$this->localpart` might not be set. This needs to be changed to work regardless of whether `getLocalPart()` method has been called first.

2016-09-15 11:29 UTC, schlessera requested changes

2016-09-15 12:45 UTC, schlessera commented on src/EmailAddress.php
> +            $this->domain = str_replace($this->localpart.'@', '', $this->address);
Also, this still uses too much memory, as you're storing the computed versions. I don't think that the processing cost is so high that you should sacrifice memory for caching the values.

2016-09-15 15:28 UTC, GaryJones commented on src/EmailAddress.php
> +            $this->domain = str_replace($this->localpart.'@', '', $this->address);
Agreed on local-part not yet being set. I'll fix that.

While processing cost is not high, once it's computed, I also don't see the memory usage being overly high from storing that value and save the exact same computation potentially being done over and over again.

2016-09-15 15:59 UTC, schlessera commented on src/EmailAddress.php
> +            $this->domain = str_replace($this->localpart.'@', '', $this->address);
Well, if you store it, the entire change is meaningless. It would only save memory if none of the individual parts are ever queried.

2016-09-15 16:02 UTC, GaryJones commented on src/EmailAddress.php
> +            $this->domain = str_replace($this->localpart.'@', '', $this->address);
With the current PR, it's only stored if it's been needed once. If no parts are ever used, nothing is stored - surely the best of both worlds?

2016-10-06 15:20 UTC, schlessera commented on src/EmailAddress.php
> +            $this->domain = str_replace($this->localpart.'@', '', $this->address);
What are the chances that you'll create a value object and not use its value in the same request? I would guess that, for the value object we're talking about here, it will be used in the large majority of cases...

2016-10-06 20:12 UTC, GaryJones commented on src/EmailAddress.php
> +            $this->domain = str_replace($this->localpart.'@', '', $this->address);
Well, the value object could be created, but perhaps only the domain is required back out of it, not the localpart.

2016-10-10 06:33 UTC, schlessera commented on src/EmailAddress.php
> +            $this->domain = str_replace($this->localpart.'@', '', $this->address);
What about turning it around? The issue is that both the complete address as well as the individual parts are stored in memory, doubling memory consumption.

How about extracting the components in `__construct()`, nut then only stored the individual parts. Getting the address is a simply concatenate then, which is very easy on the CPU.

2017-08-01 12:11 UTC, closed without merging